apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: doc-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: doc-management/auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "3001"
        - name: DB_HOST
          value: "auth-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "auth_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: password
        - name: DB_NAME
          value: "auth_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: doc-management
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP 