apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: doc-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-service
        image: doc-management/ingestion-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "3003"
        - name: DB_HOST
          value: "ingestion-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "ingestion_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ingestion-db-secret
              key: password
        - name: DB_NAME
          value: "ingestion_db"
        - name: PYTHON_BACKEND_URL
          value: "http://python-backend-service:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: doc-management
spec:
  selector:
    app: ingestion-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP 